language: python
matrix:
  include:
  # command to install dependencies
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-6
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-6"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-7
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-7"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
install: 
  - pip install -r requirements.txt
  - make install
script: 
  - make test
env: 
  TRAVIS=1
cache: 
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
